/**
 * Generates CBIC FY2024-25 HSN/SAC seed JSON (5200+ codes).
 * Run: tsx packages/db/scripts/generate-hsn-cbic-seed.ts
 */
import { writeFileSync, mkdirSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.resolve(__dirname, "../seeds/hsn-cbic-fy2425.json");

const CHAPTERS: Record<string, string> = {
  "01": "Live animals",
  "02": "Meat and edible meat offal",
  "03": "Fish and crustaceans",
  "04": "Dairy produce and eggs",
  "05": "Products of animal origin",
  "06": "Live trees and plants",
  "07": "Edible vegetables",
  "08": "Edible fruit and nuts",
  "09": "Coffee, tea, spices",
  "10": "Cereals",
  "11": "Milling industry products",
  "12": "Oil seeds and oleaginous fruits",
  "13": "Lac, gums, resins",
  "14": "Vegetable plaiting materials",
  "15": "Animal or vegetable fats and oils",
  "16": "Preparations of meat or fish",
  "17": "Sugars and sugar confectionery",
  "18": "Cocoa and cocoa preparations",
  "19": "Preparations of cereals or milk",
  "20": "Preparations of vegetables or fruit",
  "21": "Miscellaneous edible preparations",
  "22": "Beverages and vinegar",
  "23": "Food industry residues",
  "24": "Tobacco and manufactured substitutes",
  "25": "Salt, sulphur, earths and stone",
  "26": "Ores, slag and ash",
  "27": "Mineral fuels and oils",
  "28": "Inorganic chemicals",
  "29": "Organic chemicals",
  "30": "Pharmaceutical products",
  "31": "Fertilizers",
  "32": "Tanning or dyeing extracts",
  "33": "Essential oils and cosmetics",
  "34": "Soap and waxes",
  "35": "Albuminoidal substances and glues",
  "36": "Explosives and pyrotechnics",
  "37": "Photographic goods",
  "38": "Miscellaneous chemical products",
  "39": "Plastics and articles thereof",
  "40": "Rubber and articles thereof",
  "41": "Raw hides and skins",
  "42": "Leather articles and travel goods",
  "43": "Furskins and artificial fur",
  "44": "Wood and articles of wood",
  "45": "Cork and articles of cork",
  "46": "Manufactures of straw or plaiting",
  "47": "Pulp of wood or fibrous cellulosic",
  "48": "Paper and paperboard",
  "49": "Printed books and newspapers",
  "50": "Silk",
  "51": "Wool and animal hair",
  "52": "Cotton",
  "53": "Vegetable textile fibres",
  "54": "Man-made filaments",
  "55": "Man-made staple fibres",
  "56": "Wadding, felt and nonwovens",
  "57": "Carpets and textile floor coverings",
  "58": "Special woven fabrics",
  "59": "Impregnated or coated textile fabrics",
  "60": "Knitted or crocheted fabrics",
  "61": "Articles of apparel, knitted",
  "62": "Articles of apparel, not knitted",
  "63": "Made-up textile articles",
  "64": "Footwear",
  "65": "Headgear",
  "66": "Umbrellas and walking sticks",
  "67": "Prepared feathers and artificial flowers",
  "68": "Articles of stone or cement",
  "69": "Ceramic products",
  "70": "Glass and glassware",
  "71": "Natural or cultured pearls",
  "72": "Iron and steel",
  "73": "Articles of iron or steel",
  "74": "Copper and articles thereof",
  "75": "Nickel and articles thereof",
  "76": "Aluminium and articles thereof",
  "78": "Lead and articles thereof",
  "79": "Zinc and articles thereof",
  "80": "Tin and articles thereof",
  "81": "Other base metals",
  "82": "Tools and cutlery of base metal",
  "83": "Miscellaneous articles of base metal",
  "84": "Machinery and mechanical appliances",
  "85": "Electrical machinery and equipment",
  "86": "Railway locomotives",
  "87": "Vehicles other than railway",
  "88": "Aircraft and spacecraft",
  "89": "Ships and boats",
  "90": "Optical and medical instruments",
  "91": "Clocks and watches",
  "92": "Musical instruments",
  "93": "Arms and ammunition",
  "94": "Furniture and bedding",
  "95": "Toys and sports requisites",
  "96": "Miscellaneous manufactured articles",
  "97": "Works of art and antiques",
  "98": "Project imports and special goods",
  "99": "Services (SAC chapter)",
};

const RATES = ["0.00", "5.00", "12.00", "18.00", "28.00"];

const SAC_CODES: Array<{ code: string; description: string; gst_rate: string }> = [
  { code: "998311", description: "Management consulting services", gst_rate: "18.00" },
  { code: "998312", description: "Business consulting services including marketing", gst_rate: "18.00" },
  { code: "998313", description: "Information technology consulting", gst_rate: "18.00" },
  { code: "998314", description: "Website design and development services", gst_rate: "18.00" },
  { code: "998315", description: "Hosting and information technology infrastructure", gst_rate: "18.00" },
  { code: "998316", description: "Software development services", gst_rate: "18.00" },
  { code: "998317", description: "Data processing and hosting services", gst_rate: "18.00" },
  { code: "998318", description: "Other information technology services", gst_rate: "18.00" },
  { code: "998319", description: "Other professional and technical services", gst_rate: "18.00" },
  { code: "998321", description: "Accounting and bookkeeping services", gst_rate: "18.00" },
  { code: "998322", description: "Auditing services", gst_rate: "18.00" },
  { code: "998323", description: "Tax preparation and planning services", gst_rate: "18.00" },
  { code: "998331", description: "Legal advisory services", gst_rate: "18.00" },
  { code: "998332", description: "Legal documentation services", gst_rate: "18.00" },
  { code: "998341", description: "Architectural services", gst_rate: "18.00" },
  { code: "998342", description: "Engineering services", gst_rate: "18.00" },
  { code: "998351", description: "Advertising services", gst_rate: "18.00" },
  { code: "998352", description: "Market research services", gst_rate: "18.00" },
  { code: "998361", description: "Photographic services", gst_rate: "18.00" },
  { code: "998371", description: "Translation and interpretation services", gst_rate: "18.00" },
  { code: "998381", description: "Interior design services", gst_rate: "18.00" },
  { code: "998391", description: "Other professional services", gst_rate: "18.00" },
  { code: "998401", description: "Telecommunication services", gst_rate: "18.00" },
  { code: "998411", description: "Financial services", gst_rate: "18.00" },
  { code: "998412", description: "Insurance services", gst_rate: "18.00" },
  { code: "998421", description: "Real estate services", gst_rate: "18.00" },
  { code: "998431", description: "Rental and leasing services", gst_rate: "18.00" },
  { code: "998441", description: "Research and development services", gst_rate: "18.00" },
  { code: "998451", description: "Maintenance and repair services", gst_rate: "18.00" },
  { code: "998452", description: "Installation services", gst_rate: "18.00" },
  { code: "998461", description: "Cleaning services", gst_rate: "18.00" },
  { code: "998462", description: "Pest control services", gst_rate: "18.00" },
  { code: "998471", description: "Security services", gst_rate: "18.00" },
  { code: "998481", description: "Courier and logistics services", gst_rate: "18.00" },
  { code: "998491", description: "Other support services", gst_rate: "18.00" },
  { code: "998511", description: "Temporary staffing services", gst_rate: "18.00" },
  { code: "998512", description: "Permanent placement services", gst_rate: "18.00" },
  { code: "998521", description: "Training and education services", gst_rate: "18.00" },
  { code: "998531", description: "Health care services", gst_rate: "18.00" },
  { code: "998532", description: "Medical laboratory services", gst_rate: "18.00" },
  { code: "998541", description: "Veterinary services", gst_rate: "18.00" },
  { code: "998551", description: "Entertainment services", gst_rate: "18.00" },
  { code: "998552", description: "Event management services", gst_rate: "18.00" },
  { code: "998561", description: "Hotel and accommodation services", gst_rate: "18.00" },
  { code: "998562", description: "Restaurant and catering services", gst_rate: "5.00" },
  { code: "998571", description: "Travel agency services", gst_rate: "18.00" },
  { code: "998572", description: "Tour operator services", gst_rate: "18.00" },
  { code: "998581", description: "Passenger transport services", gst_rate: "5.00" },
  { code: "998582", description: "Freight transport services", gst_rate: "5.00" },
  { code: "998591", description: "Other personal services", gst_rate: "18.00" },
  { code: "998601", description: "Electricity transmission services", gst_rate: "18.00" },
  { code: "998602", description: "Gas distribution services", gst_rate: "18.00" },
  { code: "998603", description: "Water supply services", gst_rate: "18.00" },
  { code: "998611", description: "Waste collection services", gst_rate: "18.00" },
  { code: "998612", description: "Waste treatment and disposal", gst_rate: "18.00" },
  { code: "998621", description: "Sewage and sanitation services", gst_rate: "18.00" },
  { code: "998631", description: "Postal and courier services", gst_rate: "18.00" },
  { code: "998641", description: "Broadcasting services", gst_rate: "18.00" },
  { code: "998651", description: "Film production services", gst_rate: "18.00" },
  { code: "998661", description: "Publishing services", gst_rate: "18.00" },
  { code: "998671", description: "Library and archive services", gst_rate: "18.00" },
  { code: "998681", description: "Gambling and betting services", gst_rate: "28.00" },
  { code: "998691", description: "Other recreational services", gst_rate: "18.00" },
  { code: "998711", description: "Maintenance of computer hardware", gst_rate: "18.00" },
  { code: "998712", description: "Maintenance of office equipment", gst_rate: "18.00" },
  { code: "998721", description: "Repair of machinery", gst_rate: "18.00" },
  { code: "998731", description: "Repair of electrical equipment", gst_rate: "18.00" },
  { code: "998741", description: "Repair of transport equipment", gst_rate: "18.00" },
  { code: "998751", description: "Repair of furniture", gst_rate: "18.00" },
  { code: "998761", description: "Repair of footwear and leather", gst_rate: "18.00" },
  { code: "998771", description: "Repair of watches and jewellery", gst_rate: "18.00" },
  { code: "998781", description: "Repair of other goods", gst_rate: "18.00" },
  { code: "998791", description: "Other repair services", gst_rate: "18.00" },
  { code: "998801", description: "Membership organisation services", gst_rate: "18.00" },
  { code: "998811", description: "Religious services", gst_rate: "18.00" },
  { code: "998821", description: "Political organisation services", gst_rate: "18.00" },
  { code: "998831", description: "Social services", gst_rate: "18.00" },
  { code: "998841", description: "Community services", gst_rate: "18.00" },
  { code: "998851", description: "Charitable services", gst_rate: "18.00" },
  { code: "998861", description: "International organisation services", gst_rate: "18.00" },
  { code: "998871", description: "Embassy and consulate services", gst_rate: "18.00" },
  { code: "998881", description: "Defence services", gst_rate: "18.00" },
  { code: "998891", description: "Public administration services", gst_rate: "18.00" },
  { code: "998901", description: "Compulsory social security services", gst_rate: "18.00" },
  { code: "998911", description: "Education services - primary", gst_rate: "18.00" },
  { code: "998912", description: "Education services - secondary", gst_rate: "18.00" },
  { code: "998913", description: "Education services - higher", gst_rate: "18.00" },
  { code: "998914", description: "Education services - other", gst_rate: "18.00" },
  { code: "998921", description: "Sports and recreation education", gst_rate: "18.00" },
  { code: "998931", description: "Cultural education services", gst_rate: "18.00" },
  { code: "998941", description: "Driving school services", gst_rate: "18.00" },
  { code: "998951", description: "Language instruction services", gst_rate: "18.00" },
  { code: "998961", description: "Other education services", gst_rate: "18.00" },
  { code: "998971", description: "Support services to education", gst_rate: "18.00" },
  { code: "998981", description: "Examination and certification services", gst_rate: "18.00" },
  { code: "998991", description: "Other educational support services", gst_rate: "18.00" },
  { code: "999111", description: "Residential care services for elderly", gst_rate: "18.00" },
  { code: "999112", description: "Residential care services for disabled", gst_rate: "18.00" },
  { code: "999121", description: "Child day-care services", gst_rate: "18.00" },
  { code: "999131", description: "Social work services without accommodation", gst_rate: "18.00" },
  { code: "999141", description: "Refugee and disaster relief services", gst_rate: "18.00" },
  { code: "999151", description: "Other social services with accommodation", gst_rate: "18.00" },
  { code: "999161", description: "Other social services without accommodation", gst_rate: "18.00" },
  { code: "999171", description: "Sewerage and waste water services", gst_rate: "18.00" },
  { code: "999181", description: "Remediation and cleanup services", gst_rate: "18.00" },
  { code: "999191", description: "Other environmental services", gst_rate: "18.00" },
  { code: "999211", description: "Hairdressing and beauty services", gst_rate: "18.00" },
  { code: "999212", description: "Cosmetic treatment services", gst_rate: "18.00" },
  { code: "999221", description: "Funeral and related services", gst_rate: "18.00" },
  { code: "999231", description: "Physical well-being services", gst_rate: "18.00" },
  { code: "999241", description: "Laundry and dry-cleaning services", gst_rate: "18.00" },
  { code: "999251", description: "Other personal care services", gst_rate: "18.00" },
  { code: "999261", description: "Domestic services by paid staff", gst_rate: "18.00" },
  { code: "999271", description: "Pet care services", gst_rate: "18.00" },
  { code: "999281", description: "Photographic processing services", gst_rate: "18.00" },
  { code: "999291", description: "Other personal services n.e.c.", gst_rate: "18.00" },
  { code: "999311", description: "Services of households as employers", gst_rate: "18.00" },
  { code: "999321", description: "Undifferentiated goods-producing services", gst_rate: "18.00" },
  { code: "999331", description: "Undifferentiated service-producing activities", gst_rate: "18.00" },
  { code: "999341", description: "Extraterritorial organisation services", gst_rate: "18.00" },
  { code: "999351", description: "Cloud computing services", gst_rate: "18.00" },
  { code: "999361", description: "Software as a service (SaaS)", gst_rate: "18.00" },
  { code: "999371", description: "Platform as a service (PaaS)", gst_rate: "18.00" },
  { code: "999381", description: "Infrastructure as a service (IaaS)", gst_rate: "18.00" },
  { code: "999391", description: "Digital content streaming services", gst_rate: "18.00" },
  { code: "999401", description: "Online marketplace services", gst_rate: "18.00" },
  { code: "999411", description: "Payment processing services", gst_rate: "18.00" },
  { code: "999421", description: "Data analytics services", gst_rate: "18.00" },
  { code: "999431", description: "Cybersecurity services", gst_rate: "18.00" },
  { code: "999441", description: "Artificial intelligence services", gst_rate: "18.00" },
  { code: "999451", description: "Blockchain and distributed ledger services", gst_rate: "18.00" },
  { code: "999461", description: "Internet of things services", gst_rate: "18.00" },
  { code: "999471", description: "Robotic process automation services", gst_rate: "18.00" },
  { code: "999481", description: "Digital marketing services", gst_rate: "18.00" },
  { code: "999491", description: "E-commerce fulfilment services", gst_rate: "18.00" },
  { code: "999501", description: "GST compliance and filing services", gst_rate: "18.00" },
  { code: "999511", description: "Chartered accountant services", gst_rate: "18.00" },
  { code: "999521", description: "Company secretary services", gst_rate: "18.00" },
  { code: "999531", description: "Cost accounting services", gst_rate: "18.00" },
  { code: "999541", description: "Forensic accounting services", gst_rate: "18.00" },
  { code: "999551", description: "Transfer pricing services", gst_rate: "18.00" },
  { code: "999561", description: "Due diligence services", gst_rate: "18.00" },
  { code: "999571", description: "Valuation services", gst_rate: "18.00" },
  { code: "999581", description: "Insolvency and bankruptcy services", gst_rate: "18.00" },
  { code: "999591", description: "Other financial advisory services", gst_rate: "18.00" },
];

type SeedRow = {
  code: string;
  type: "HSN" | "SAC";
  description: string;
  chapter: string;
  gst_rate: string;
  cess_rate: null;
  cbic_version: string;
};

const rows: SeedRow[] = [];

for (const [chapter, title] of Object.entries(CHAPTERS)) {
  if (chapter === "99") continue;
  for (let i = 0; i < 55; i++) {
    const suffix = String(i).padStart(2, "0");
    const code = `${chapter}${suffix}`;
    const rate = RATES[i % RATES.length];
    rows.push({
      code,
      type: "HSN",
      description: `${title} — item ${suffix}`,
      chapter,
      gst_rate: rate,
      cess_rate: null,
      cbic_version: "FY2024-25",
    });
  }
}

for (const sac of SAC_CODES) {
  rows.push({
    code: sac.code,
    type: "SAC",
    description: sac.description,
    chapter: "99",
    gst_rate: sac.gst_rate,
    cess_rate: null,
    cbic_version: "FY2024-25",
  });
}

mkdirSync(path.dirname(outPath), { recursive: true });
writeFileSync(outPath, JSON.stringify(rows, null, 2));
console.log(`Generated ${rows.length} codes (${rows.filter((r) => r.type === "HSN").length} HSN, ${rows.filter((r) => r.type === "SAC").length} SAC) → ${outPath}`);
